### PR TITLE
Disable cpio strategy

### PR DESCRIPTION
**Pull request by Ana06**
If it is disabled it won't work. Confusing to read. :confused:

### CODE REVIEW

**Comment by ChrisBr** [comment]
> If it is disabled it won't work.

It will not run on the server, correct! But it in general it will work, you just need to trigger it manually with ``osc service disabledrun``

I would keep it till everything is in place on build.o.o

Other opinions @jordimassaguerpla ?

**Comment by jordimassaguerpla** [comment]
I think it is confusing that in the README you see sometimes "mode=disabled" and sometimes not. I think we should be consistent across the whole file.

**Comment by ChrisBr** [comment]
Currently it is disabled everywhere in the readme

**Comment by jordimassaguerpla** [comment]
The "resulting _service file" is not disabled. I would either add the disabled mode there or remove it elsewhere. Not a big deal, but just to be consistent.

**Comment by Ana06** [comment]
@jordimassaguerpla 

> The "resulting _service file" is not disabled. I would either add the disabled mode there or remove it elsewhere. Not a big deal, but just to be consistent.

it sounds reasonable. :+1:

**Comment by ChrisBr** [comment]
Closing, covered in https://github.com/openSUSE/obs-service-bundle_gems/pull/11

**Pull request closed without merging**
